## This file loads the required packages for 
## reproducing the results of the paper "Regional Birth Squeezes: A cross-country comparison"

# Load the packages
library(tidyverse)
library(data.table)
library(dtplyr)
library(reshape2)
library(naniar)
library(survey)
library(haven)
library(scales)
library(httr)
library(rvest)
library(jsonlite)
library(readxl)
library(pxweb)
library(httr)
library(janitor)
library(parallel)
library(rvest)
library(sf)
library(ggspatial)
library(rnaturalearth)
library(rnaturalearthdata)
library(HMDHFDplus)
library(pander)
library(patchwork)
library(haven)
library(MatchIt)
library(cem)
library(sjlabelled)
library(readstata13)
library(splines)
